name: Build Actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13, ubuntu-latest]
    steps:
      - uses: swift-actions/setup-swift@v1
        if: runner.os == 'Linux'
        with:
          swift-version: "5.8"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test -c release
        env:
          CI: 1
